-- CORREÇÃO FINAL PARA A TABELA LEADS
-- Cole e rode este script no SQL Editor

ALTER TABLE public.leads 
ADD COLUMN IF NOT EXISTS contact TEXT,
ADD COLUMN IF NOT EXISTS company TEXT,
ADD COLUMN IF NOT EXISTS role TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS email TEXT;
